language: ruby
rvm:
  - 1.8.7
  - 2.1.6
  - 2.2.1
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - "bundle exec rspec"
before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
  
