language: ruby
rvm:
  - 1.8.7
  - 1.9.2  
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - "cd ./spec/dummy && RAILS_ENV=test bundle exec rake --trace db:migrate && cd ../../ && rspec"
before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
  
